# Basic Python

## 1. Split this string

In [1]:
s = "Hi Iam Siva H!"

In [2]:
print(s.split())

['Hi', 'Iam', 'Siva', 'H!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Mars is 12742 kilometers.

In [3]:
planet = "Mars"
diameter = 12742

In [4]:
print('The diameter of {} is {} kilometers'.format(planet,diameter))

The diameter of Mars is 12742 kilometers


## 3. In this nest dictionary grab the word "moon"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'moon']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'moon'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 20 zeros? 
## 4.2 Create an array of 20 fives?

In [9]:
np.zeros([20])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
np.ones([20])+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

## 5. Create an array of all the even integers from 30 to 45

In [10]:
even = np.arange(30,45,2)
print(even)

[30 32 34 36 38 40 42 44]


## 6. Create a 3x3 matrix with values ranging from 1 to 10

In [11]:
mat = np.arange(1,10).reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 7. Concatinate a and b 
## a = np.array([4, 5, 6]), b = np.array([7, 8, 9])

In [12]:
a = np.array([4, 5, 6])
b = np.array([7, 8, 9])
np.concatenate((a,b),axis=0)

array([4, 5, 6, 7, 8, 9])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data = {'name':['ravi','ram','suresh'],'age':[20,21,22]}
df = pd.DataFrame(data)
df

name  age
0    ravi   20
1     ram   21
2  suresh   22

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import date, timedelta



<generator object dates_bwn_twodates at 0x7fe61b6a3e50>


In [ ]:
import pandas
pandas.date_range(sdate,edate-timedelta(days=1),freq='d')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
      

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24